sylius_paypal_webhook:
    resource: "@SyliusPayPalPlugin/Resources/config/webhook_routing.yaml"

app_admin_catalog_promotion:
    resource: |
        alias: app.catalog_promotion
        section: admin
        templates: "@SyliusAdmin\\Crud"
        redirect: update
        grid: app_admin_catalog_promotion
        vars:
            all:
                subheader: app.ui.catalog_promotion
            index:
                icon: 'file image outline'
    type: sylius.resource
    prefix: /admin
